FROM apache/airflow:2.10.2-python3.11

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create directory for MLflow tracking cache and set permissions
RUN mkdir -p /opt/mlflow && chown airflow /opt/mlflow

USER airflow
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --default-timeout=1000 -r /tmp/requirements.txt
